Correct typos & Documentation of the algorithm parameter
w3c-ccg/http-signatures pull request #60
Opened 2019-05-14 13:29 UTC by aljones15

Corrects Issue:
https://github.com/w3c-dvcg/http-signatures/issues/59

2019-05-14 22:00 UTC, dlongley requested changes

2019-05-14 22:00 UTC, dlongley commented on index.xml
> +from the keyId and the digital signature algorithm specified in the key's metadata.
Added `associated` and the backticks back and I think saying that the algorithm is specified in the key's metadata is problematic because we don't actually specify that anywhere (intentionally). We just want to say that the algorithm is associated with the key and how that's done is out of scope for this spec. I'm not sure if this change will suffice to cover all that, but here it is:

```suggestion
associated with the `keyId` according to its digital signature algorithm.
```

Note: This isn't specific to this one change, but I do wonder if we'll get any complaints by lumping HMAC in with "digital signature" since it doesn't provide non-repudiation. We talk about "digital signatures" as an umbrella that includes HMACs throughout the spec.

2019-05-14 22:00 UTC, dlongley commented on index.xml
> -The client uses the `algorithm` and `headers` Signature Parameters to form a
We can't remove `algorithm` yet because we're using it to specify `hs2019` which *does* influence how the canonized string is formed.

2019-05-14 22:00 UTC, dlongley commented on index.xml
> +The value MUST be a Unix timestamp integer value. A signatures with an
```suggestion
The value MUST be a Unix timestamp integer value. A signature with an
```

2019-05-14 22:32 UTC, aljones15 commented on index.xml
> -The client uses the `algorithm` and `headers` Signature Parameters to form a
you might want to make that more specific as in this issue: 
https://github.com/w3c-dvcg/http-signatures/issues/59

both myself and @RayTrommelenInfoSupport
are a bit confused on this.

so this means
algorithm is RECOMMEND which means if it is not implemented then the implementation must default to a digital signature algorithm for all signings and verifications which is not deprecated.

on the other hand if algorithm is implemented it is used to determine the hash algorithm (if any) and then they key type is derived from the key metadata and checked to make sure it is in the signature algorithm's key types?

2019-05-14 23:08 UTC, aljones15 commented
@dlongley 

> Implementers SHOULD derive the digital
> signature algorithm used by an implementation from the key metadata identified
> by the `keyId` rather than from this field.

this really suggests everything comes from the metadata now.

2019-05-20 11:13 UTC, liamdennehy commented
As pointed out, there are two directives in the algorithm field: the digitial signature algorithm, and the hash algorithm to generate the input to the DSA.

The DSA is indeed derived from the metadata of the key, but the hash algorithm absolutely can not. Should the verifier rather permit specification of the DSA, but reject an algorithm that does not match the key metadata, and then respect the hash algorithm selection (within any policy on acceptable hash algorithms specified by the implementation)?

In any case, the hash algorithm MUST be specified as it simply cannot be derived independently.

2019-05-20 12:53 UTC, aljones15 commented
@liamdennehy no issues with that, but I do think the spec needs to better clarify that usage and hopefully the changes in this Pr address that somewhat.

2019-10-11 14:47 UTC, liamdennehy approved these changes

2019-10-11 14:47 UTC, merged